# -*- coding: utf-8 -*-
"""LabTask2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a76xi5BcxOk5-z9ReOWO_JuzOePzt85s
"""

class Trapezoid:
    def __init__(self, a, b, h):
        self.a = a
        self.b = b
        self.h = h

    def area(self):
        return 0.5 * (self.a + self.b) * self.h


class Parallelogram:
    def __init__(self, base, height):
        self.base = base
        self.height = height

    def area(self):
        return self.base * self.height


areas = {}

inputs = [
    (10, 8, 5, 6, 7),
    (12, 6, 4, 5, 10),
    (7, 9, 3, 8, 6)
]

for i, (a, b, h, base, height) in enumerate(inputs):
    t = Trapezoid(a, b, h)
    p = Parallelogram(base, height)

    areas[f"Trapezoid_{i+1}"] = t.area()
    areas[f"Parallelogram_{i+1}"] = p.area()

print("\nAreas Dictionary:")
for k, v in areas.items():
    print(f"{k}: {v}")

max_shape = max(areas, key=areas.get)
print("\nShape with maximum area:", max_shape)
print("Maximum area value:", areas[max_shape])