# -*- coding: utf-8 -*-
"""LabTask1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zu7FL_b7VtUouTpwzH9KQ3bCqIyT-Jl
"""

class MyClass:
    def __init__(self, x, y):
        self.x = x
        self.y = y

obj = MyClass(10, 20)
print("1. Namespace of instance:", obj.__dict__)


def student_data(student_id, name=None, student_class=None):
    print(f"\n2. Student ID: {student_id}")
    if name:
        print(f"Name: {name}")
    if student_class:
        print(f"Class: {student_class}")

student_data(101)
student_data(102, "Ali", "BSCS")


class Student:
    pass

print("\n3. Type of Student class:", type(Student))
print("Keys of __dict__:", Student.__dict__.keys())
print("Module of class:", Student.__module__)


class Student:
    pass

class Marks:
    pass

s = Student()
m = Marks()

print("\n4. Instance checks:")
print(isinstance(s, Student))
print(isinstance(m, Marks))
print(issubclass(Student, object))
print(issubclass(Marks, object))


class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

stu = Student("Ali", 85)
print("\n5. Original:", stu.name, stu.marks)

stu.name = "Ahmed"
stu.marks = 90
print("Updated:", stu.name, stu.marks)


class Student:
    def __init__(self, sid, name):
        self.sid = sid
        self.name = name

stu = Student(1, "Ali")
stu.student_class = "BSCS"

print("\n6. Before deletion:", stu.__dict__)

del stu.name
print("After deletion:", stu.__dict__)


class Student:
    def __init__(self, sid, name, sclass):
        self.sid = sid
        self.name = name
        self.sclass = sclass

    def display(self):
        print("\n7. Student Attributes:")
        for key, value in self.__dict__.items():
            print(f"{key}: {value}")

stu = Student(1, "Ali", "BSCS")
stu.display()


student1 = Student(1, "Zohaib", "BSCS")
student2 = Student(2, "Ali", "BSE")

print("\n8. Student Records:")
for s in [student1, student2]:
    print(s.__dict__)


import sys

print("\n9. Memory usage of one student object:", sys.getsizeof(student1))


class StudentOptimized:
    __slots__ = ['sid', 'name', 'sclass']

    def __init__(self, sid, name, sclass):
        self.sid = sid
        self.name = name
        self.sclass = sclass

opt = StudentOptimized(1, "Ali", "BSCS")

print("\n10. Optimized object memory:", sys.getsizeof(opt))