# -*- coding: utf-8 -*-
"""UCS_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13653WRC9AxEDy1s8-7ua1OcTdWFx2VMQ
"""

import heapq

def uniform_cost_search(graph, start, goal):
    # Priority Queue stores (cost, current_node, path)
    priority_queue = [(0, start, [start])]
    visited = set()

    while priority_queue:
        # Pop the node with the lowest cumulative cost
        cost, current_node, path = heapq.heappop(priority_queue)

        if current_node in visited:
            continue

        # Check if we reached the goal
        if current_node == goal:
            return path, cost

        visited.add(current_node)

        # Explore neighbors
        for neighbor, weight in graph.get(current_node, []):
            if neighbor not in visited:
                total_cost = cost + weight
                heapq.heappush(priority_queue, (total_cost, neighbor, path + [neighbor]))

    return None, float('inf')

# Graph representation based on your image
# Format: 'Node': [('Neighbor', cost), ...]
graph = {
    'F': [('C', 5)],
    'C': [('A', 4)],
    'A': [('B', 1)],
    'B': [('E', 3), ('P', 1)],
    'E': [('P', 1)],
    'P': [('G', 2)],
    'G': []
}

# Run the search
start_node = 'F'
goal_node = 'G'
optimal_path, total_min_cost = uniform_cost_search(graph, start_node, goal_node)

print(f"Optimal Path from {start_node} to {goal_node}: {' -> '.join(optimal_path)}")
print(f"Total Minimum Cost: {total_min_cost}")